// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvihzvxnvzppyuhrulhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2aWh6dnhudnpwcHl1aHJ1bGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzU5MDAsImV4cCI6MjA3MDE1MTkwMH0.iBN2btJRZW6pH10W_VX6dLIZvtMOj6NcsVxnOMIUR80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});